### ISSUE TITLE
Can the JS icon be yellow?

### ISSUE THREAD

**Issue by Tyriar** [be5invis/vscode-iconset#5]
The (unofficial) [logo of JavaSrcript](http://3.bp.blogspot.com/-PTty3CfTGnA/TpZOEjTQ_WI/AAAAAAAAAeo/KeKt_D5X2xo/s1600/js.jpg) is a pale yellow color, any reason the JS icon is orange?

**Comment by be5invis** [comment]
The color of languages are (mostly) following the original colors of Visual Studio, except for TypeScript, I prefer blue instead of “TS Orange”.
![image](https://cloud.githubusercontent.com/assets/240091/18757285/d6321242-8125-11e6-8bc8-3626550874a4.png)

Anyway, the colors are driven by palettes in the `.ai` file.

**Comment by Tyriar** [comment]
:+1:
